/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.Festival.common;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-04-20")
public class Bilet implements org.apache.thrift.TBase<Bilet, Bilet._Fields>, java.io.Serializable, Cloneable, Comparable<Bilet> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Bilet");

  private static final org.apache.thrift.protocol.TField CONCERT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("concertID", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CUSTOMER_FIELD_DESC = new org.apache.thrift.protocol.TField("customer", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SEATS_FIELD_DESC = new org.apache.thrift.protocol.TField("seats", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BiletStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BiletTupleSchemeFactory();

  public int concertID; // required
  public @org.apache.thrift.annotation.Nullable String customer; // required
  public int seats; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CONCERT_ID((short)1, "concertID"),
    CUSTOMER((short)2, "customer"),
    SEATS((short)3, "seats");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CONCERT_ID
          return CONCERT_ID;
        case 2: // CUSTOMER
          return CUSTOMER;
        case 3: // SEATS
          return SEATS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CONCERTID_ISSET_ID = 0;
  private static final int __SEATS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CONCERT_ID, new org.apache.thrift.meta_data.FieldMetaData("concertID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CUSTOMER, new org.apache.thrift.meta_data.FieldMetaData("customer", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SEATS, new org.apache.thrift.meta_data.FieldMetaData("seats", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Bilet.class, metaDataMap);
  }

  public Bilet() {
  }

  public Bilet(
    int concertID,
    String customer,
    int seats)
  {
    this();
    this.concertID = concertID;
    setConcertIDIsSet(true);
    this.customer = customer;
    this.seats = seats;
    setSeatsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Bilet(Bilet other) {
    __isset_bitfield = other.__isset_bitfield;
    this.concertID = other.concertID;
    if (other.isSetCustomer()) {
      this.customer = other.customer;
    }
    this.seats = other.seats;
  }

  public Bilet deepCopy() {
    return new Bilet(this);
  }

  @Override
  public void clear() {
    setConcertIDIsSet(false);
    this.concertID = 0;
    this.customer = null;
    setSeatsIsSet(false);
    this.seats = 0;
  }

  public int getConcertID() {
    return this.concertID;
  }

  public Bilet setConcertID(int concertID) {
    this.concertID = concertID;
    setConcertIDIsSet(true);
    return this;
  }

  public void unsetConcertID() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CONCERTID_ISSET_ID);
  }

  /** Returns true if field concertID is set (has been assigned a value) and false otherwise */
  public boolean isSetConcertID() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CONCERTID_ISSET_ID);
  }

  public void setConcertIDIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CONCERTID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public String getCustomer() {
    return this.customer;
  }

  public Bilet setCustomer(@org.apache.thrift.annotation.Nullable String customer) {
    this.customer = customer;
    return this;
  }

  public void unsetCustomer() {
    this.customer = null;
  }

  /** Returns true if field customer is set (has been assigned a value) and false otherwise */
  public boolean isSetCustomer() {
    return this.customer != null;
  }

  public void setCustomerIsSet(boolean value) {
    if (!value) {
      this.customer = null;
    }
  }

  public int getSeats() {
    return this.seats;
  }

  public Bilet setSeats(int seats) {
    this.seats = seats;
    setSeatsIsSet(true);
    return this;
  }

  public void unsetSeats() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SEATS_ISSET_ID);
  }

  /** Returns true if field seats is set (has been assigned a value) and false otherwise */
  public boolean isSetSeats() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SEATS_ISSET_ID);
  }

  public void setSeatsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SEATS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case CONCERT_ID:
      if (value == null) {
        unsetConcertID();
      } else {
        setConcertID((Integer)value);
      }
      break;

    case CUSTOMER:
      if (value == null) {
        unsetCustomer();
      } else {
        setCustomer((String)value);
      }
      break;

    case SEATS:
      if (value == null) {
        unsetSeats();
      } else {
        setSeats((Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CONCERT_ID:
      return getConcertID();

    case CUSTOMER:
      return getCustomer();

    case SEATS:
      return getSeats();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CONCERT_ID:
      return isSetConcertID();
    case CUSTOMER:
      return isSetCustomer();
    case SEATS:
      return isSetSeats();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Bilet)
      return this.equals((Bilet)that);
    return false;
  }

  public boolean equals(Bilet that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_concertID = true;
    boolean that_present_concertID = true;
    if (this_present_concertID || that_present_concertID) {
      if (!(this_present_concertID && that_present_concertID))
        return false;
      if (this.concertID != that.concertID)
        return false;
    }

    boolean this_present_customer = true && this.isSetCustomer();
    boolean that_present_customer = true && that.isSetCustomer();
    if (this_present_customer || that_present_customer) {
      if (!(this_present_customer && that_present_customer))
        return false;
      if (!this.customer.equals(that.customer))
        return false;
    }

    boolean this_present_seats = true;
    boolean that_present_seats = true;
    if (this_present_seats || that_present_seats) {
      if (!(this_present_seats && that_present_seats))
        return false;
      if (this.seats != that.seats)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + concertID;

    hashCode = hashCode * 8191 + ((isSetCustomer()) ? 131071 : 524287);
    if (isSetCustomer())
      hashCode = hashCode * 8191 + customer.hashCode();

    hashCode = hashCode * 8191 + seats;

    return hashCode;
  }

  @Override
  public int compareTo(Bilet other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetConcertID()).compareTo(other.isSetConcertID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConcertID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.concertID, other.concertID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCustomer()).compareTo(other.isSetCustomer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCustomer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.customer, other.customer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSeats()).compareTo(other.isSetSeats());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSeats()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.seats, other.seats);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Bilet(");
    boolean first = true;

    sb.append("concertID:");
    sb.append(this.concertID);
    first = false;
    if (!first) sb.append(", ");
    sb.append("customer:");
    if (this.customer == null) {
      sb.append("null");
    } else {
      sb.append(this.customer);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("seats:");
    sb.append(this.seats);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BiletStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BiletStandardScheme getScheme() {
      return new BiletStandardScheme();
    }
  }

  private static class BiletStandardScheme extends org.apache.thrift.scheme.StandardScheme<Bilet> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Bilet struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CONCERT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.concertID = iprot.readI32();
              struct.setConcertIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CUSTOMER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.customer = iprot.readString();
              struct.setCustomerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SEATS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.seats = iprot.readI32();
              struct.setSeatsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Bilet struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CONCERT_ID_FIELD_DESC);
      oprot.writeI32(struct.concertID);
      oprot.writeFieldEnd();
      if (struct.customer != null) {
        oprot.writeFieldBegin(CUSTOMER_FIELD_DESC);
        oprot.writeString(struct.customer);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SEATS_FIELD_DESC);
      oprot.writeI32(struct.seats);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BiletTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BiletTupleScheme getScheme() {
      return new BiletTupleScheme();
    }
  }

  private static class BiletTupleScheme extends org.apache.thrift.scheme.TupleScheme<Bilet> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Bilet struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetConcertID()) {
        optionals.set(0);
      }
      if (struct.isSetCustomer()) {
        optionals.set(1);
      }
      if (struct.isSetSeats()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetConcertID()) {
        oprot.writeI32(struct.concertID);
      }
      if (struct.isSetCustomer()) {
        oprot.writeString(struct.customer);
      }
      if (struct.isSetSeats()) {
        oprot.writeI32(struct.seats);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Bilet struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.concertID = iprot.readI32();
        struct.setConcertIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.customer = iprot.readString();
        struct.setCustomerIsSet(true);
      }
      if (incoming.get(2)) {
        struct.seats = iprot.readI32();
        struct.setSeatsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

