/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Festival
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Bilet : TBase
  {
    private int _concertID;
    private string _customer;
    private int _seats;

    public int ConcertID
    {
      get
      {
        return _concertID;
      }
      set
      {
        __isset.concertID = true;
        this._concertID = value;
      }
    }

    public string Customer
    {
      get
      {
        return _customer;
      }
      set
      {
        __isset.customer = true;
        this._customer = value;
      }
    }

    public int Seats
    {
      get
      {
        return _seats;
      }
      set
      {
        __isset.seats = true;
        this._seats = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool concertID;
      public bool customer;
      public bool seats;
    }

    public Bilet() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                ConcertID = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Customer = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                Seats = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Bilet");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.concertID) {
          field.Name = "concertID";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ConcertID);
          oprot.WriteFieldEnd();
        }
        if (Customer != null && __isset.customer) {
          field.Name = "customer";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Customer);
          oprot.WriteFieldEnd();
        }
        if (__isset.seats) {
          field.Name = "seats";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Seats);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Bilet(");
      bool __first = true;
      if (__isset.concertID) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ConcertID: ");
        __sb.Append(ConcertID);
      }
      if (Customer != null && __isset.customer) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Customer: ");
        __sb.Append(Customer);
      }
      if (__isset.seats) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Seats: ");
        __sb.Append(Seats);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
